# microservice-configs/producer-service.yml

server:
  port: 8081

spring:
  application:
    name: producer-service

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

app:
  message: "This is producer-service"
